#!/bin/sh

#for rtlinux-3.1

#remove rt_process
/sbin/rmmod rt_process

#remove comedi modules  ... commented if comedi loaded by /etc/rc.d/rc.local
#/sbin/rmmod ni_atmio
#/sbin/rmmod kcomedilib
#/sbin/rmmod comedi

#remove RT modules
#/sbin/rmmod rtl_fifo
#/sbin/rmmod rtl_posixio
#/sbin/rmmod rtl_sched
#/sbin/rmmod rtl_time  #... commented if comedi loaded by /etc/rc.d/rc.local

#remove the mbuff shared memory module
#/sbin/rmmod mbuff

#/bin/chown -R daq.daq /home-ep/daq/rtlinux/daq_system/data   

