#!/bin/bash

if [ ! -e "$LINUXDIR/.config" ]; then
	cat <<EOF
 *****    ERROR!!!
 *****
 *****    You need to run make config and make dep on the kernel in
 *****    ${LINUXDIR} (.config in kernel directory not found!)
EOF
	exit 1
fi


if grep -q "CONFIG_RTLINUX=" ${LINUXDIR}/.config; then
	RTOS=RTLINUX
elif grep -q "CONFIG_RTHAL=" ${LINUXDIR}/.config; then
	RTOS=RTAI
else
	RTOS=""
	cat <<EOF
 *****    ERROR!!!
 *****
 *****    Your kernel needs to be compiled and patched with either
 *****    RTAI or RTLinux 3.1+ support!
EOF
	exit 1
fi



