/***************************************************************************
                          testieview.h  -  description
                             -------------------
    begin                : Fri Aug  3 15:03:46 EDT 2001
    copyright            : (C) 2001 by Calin Culianu
    email                : calin@rtlab.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef TESTIEVIEW_H
#define TESTIEVIEW_H

// include files for Qt
#include <qwidget.h>

class TestieDoc;

/**
 * This class provides an incomplete base for your application view.
 * 	
 * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
 * @version KDevelop version 1.1 code generation
 */
class TestieView : public QWidget
{
  Q_OBJECT

  friend TestieDoc;

  public:
    /** Constructor for the view
    	* @param pDoc  your document instance that the view represents. Create a document before calling the constructor
    	* or connect an already existing document to a new MDI child widget.*/
    TestieView(TestieDoc* pDoc, QWidget* parent, const char *name, int wflags);
    /** Destructor for the main view */
    ~TestieView();
		/** returns a pointer to the document connected to the view*/
    TestieDoc *getDocument() const;
    /** gets called to redraw the document contents if it has been modified */
		void update(TestieView* pSender);
    /** contains the implementation for printing functionality and gets called by TestieApp::slotFilePrint() */
    void print(QPrinter *pPrinter);
		
  protected:
	  virtual void closeEvent(QCloseEvent*);

	  TestieDoc *doc;
	
  private:
	
};

#endif
